[tool.poetry]
name = "mqtt-communication-checker"
version = "2.0.0"
description = "Local MQTT communication checker"
authors = ["Stefano Cappa"]
readme = "README.md"
packages = [
    {include = "src"}
]

[tool.poetry.scripts]
mqtt-communication-checker = "src.__main__:main"

[tool.poetry.dependencies]
python = "^3.12"
paho-mqtt = "^2.1.0"
pymongo = "^4.11.1"
redis = "^5.2.1"
cryptography = "^48.0.0"
pydantic = "^2.11.7"
questionary = "^2.1.0"

[tool.poetry.group.dev.dependencies]
pyrefly = "^1.0.0"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
]
check-unannotated-defs = true
infer-return-types = "checked"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
